#ifndef DASH_CHAINPARAMSSEEDS_H
#define DASH_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the dash network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
        {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x50,0xd1,0xfd,0x2c}, 10111}
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // DASH_CHAINPARAMSSEEDS_H